# Generated by Django 4.0.6 on 2022-07-16 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings_investments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavingsInvestments',
            new_name='SavingInvestment',
        ),
    ]
