# Generated by Django 4.0.6 on 2022-07-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recommended_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
